#!/usr/bin/env bash
# publish-homebrew-formula.sh — compute the universal DMG SHA256 from a
# GitHub release and open a PR against the Homebrew tap with the updated cask.
#
# Usage:
#   ./scripts/publish-homebrew-formula.sh v1.1.0
#
# Requirements:
#   - gh (authenticated against both vellankikoti/kubilitics and
#     vellankikoti/homebrew-kubilitics)
#   - local clone of the tap at $TAP_PATH (default: ../homebrew-kubilitics)

set -euo pipefail

TAG="${1:?usage: $0 vX.Y.Z}"
VERSION="${TAG#v}"
TAP_PATH="${TAP_PATH:-../homebrew-kubilitics}"

if [ ! -d "$TAP_PATH" ]; then
  echo "ERROR: Homebrew tap clone not found at $TAP_PATH" >&2
  echo "       Clone https://github.com/vellankikoti/homebrew-kubilitics first" >&2
  exit 1
fi

# Fetch the DMG checksum from the release's checksums.txt asset.
echo "Downloading checksums.txt for $TAG"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
gh release download "$TAG" --repo vellankikoti/kubilitics --pattern "checksums.txt" --dir "$TMP"

DMG_SHA=$(awk "/Kubilitics_${VERSION}_universal\\.dmg\$/ {print \$1}" "$TMP/checksums.txt")

if [ -z "$DMG_SHA" ]; then
  echo "ERROR: universal DMG entry not found in checksums.txt:" >&2
  cat "$TMP/checksums.txt" >&2
  exit 1
fi

echo "universal dmg sha: $DMG_SHA"

# Copy the canonical cask into the tap with version + SHA substituted.
mkdir -p "$TAP_PATH/Casks"
cp deploy/homebrew/kubilitics.rb "$TAP_PATH/Casks/kubilitics.rb"
sed -i.bak "s|^  version \"[^\"]*\"|  version \"$VERSION\"|" "$TAP_PATH/Casks/kubilitics.rb"
sed -i.bak "s|^  sha256 \"[^\"]*\"|  sha256 \"$DMG_SHA\"|" "$TAP_PATH/Casks/kubilitics.rb"
rm -f "$TAP_PATH/Casks/kubilitics.rb.bak"

cd "$TAP_PATH"
BRANCH="release/$TAG"
git checkout -B "$BRANCH"
git add Casks/kubilitics.rb
git commit -m "release: Kubilitics $TAG"
git push -u origin "$BRANCH"

gh pr create \
  --repo vellankikoti/homebrew-kubilitics \
  --title "release: Kubilitics $TAG" \
  --body "Auto-generated by publish-homebrew-formula.sh from checksums.txt." \
  --base main --head "$BRANCH"

echo "✓ PR opened on vellankikoti/homebrew-kubilitics for $TAG"
